FROM node:24

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY apps/http-server/package.json apps/http-server/package.json
COPY apps/web/package.json apps/web/package.json
COPY apps/ws-server/package.json apps/ws-server/package.json
COPY packages/prisma/package.json packages/prisma/package.json
COPY packages/typescript-config/package.json packages/typescript-config/package.json
COPY packages/eslint-config/package.json packages/eslint-config/package.json
COPY packages/ui/package.json packages/ui/package.json

RUN pnpm install

COPY . .

ARG DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"
ENV DATABASE_URL=$DATABASE_URL

RUN pnpm --filter @repo/prisma run db:generate
RUN pnpm --filter @repo/prisma run build

RUN pnpm --filter http-server run build

EXPOSE 3001

CMD ["sh", "-c", "pnpm --filter @repo/prisma run db:deploy && pnpm --filter http-server run start"]